language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

sudo: required

install:
  - git clone https://github.com/jacekkow/uphpCAS-tests tests
  - ./tests/install.sh

script:
  - ./tests/script.sh
